/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as ReserveRouteImport } from './routes/reserve'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantsIdRouteImport } from './routes/restaurants.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveRoute = ReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIdRoute = RestaurantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RestaurantsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/menu': typeof MenuRoute
  '/reserve': typeof ReserveRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/menu': typeof MenuRoute
  '/reserve': typeof ReserveRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/menu': typeof MenuRoute
  '/reserve': typeof ReserveRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/menu'
    | '/reserve'
    | '/restaurants'
    | '/sitemap.xml'
    | '/restaurants/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/menu'
    | '/reserve'
    | '/restaurants'
    | '/sitemap.xml'
    | '/restaurants/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/menu'
    | '/reserve'
    | '/restaurants'
    | '/sitemap.xml'
    | '/restaurants/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  MenuRoute: typeof MenuRoute
  ReserveRoute: typeof ReserveRoute
  RestaurantsRoute: typeof RestaurantsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve': {
      id: '/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof ReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$id': {
      id: '/restaurants/$id'
      path: '/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof RestaurantsIdRouteImport
      parentRoute: typeof RestaurantsRoute
    }
  }
}

interface RestaurantsRouteChildren {
  RestaurantsIdRoute: typeof RestaurantsIdRoute
}

const RestaurantsRouteChildren: RestaurantsRouteChildren = {
  RestaurantsIdRoute: RestaurantsIdRoute,
}

const RestaurantsRouteWithChildren = RestaurantsRoute._addFileChildren(
  RestaurantsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  MenuRoute: MenuRoute,
  ReserveRoute: ReserveRoute,
  RestaurantsRoute: RestaurantsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
